version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20
      python: 3.11
    commands:
      - echo "Installing AWS CDK CLI..."
      - npm install -g aws-cdk@latest
      - cd Backend
      - npm install

  pre_build:
    commands:
      - echo "=== Building TypeScript ==="
      - npm run build
      - echo "✅ TypeScript build completed"
      - echo "=== Installing Lambda dependencies ==="
      - cd lambda && pip install -r requirements.txt -t . && cd ..
      - echo "✅ Lambda dependencies installed"
      - echo "=== Bootstrapping CDK Environment ==="
      - |
        # Set default PROJECT_NAME for bootstrap if not provided
        if [ -z "$PROJECT_NAME" ]; then
          PROJECT_NAME="abc"
        fi
        cdk bootstrap --require-approval never \
          --context projectName="$PROJECT_NAME" \
          --context modelId="${MODEL_ID:-anthropic.claude-3-haiku-20240307-v1:0}" \
          --context embeddingModelId="${EMBEDDING_MODEL_ID:-amazon.titan-embed-text-v1}"
      - echo "✅ CDK Bootstrap completed"

  build:
    commands:
      - |
        if [ "$ACTION" = "destroy" ]; then
          echo "=== Destroying Stack ==="
          cdk destroy AmericasBloodCentersBedrockStack --force \
            --context projectName="$PROJECT_NAME" \
            --context modelId="$MODEL_ID" \
            --context embeddingModelId="$EMBEDDING_MODEL_ID"
          echo "✅ Stack destroyed successfully"
        else
          echo "========================================="
          echo "Deploying America's Blood Centers Bedrock Chatbot"
          echo "========================================="
          
          echo "=== CDK Infrastructure Deployment ==="
          
          # Set default PROJECT_NAME if not provided
          if [ -z "$PROJECT_NAME" ]; then
            PROJECT_NAME="abc"
            echo "🔍 Using default PROJECT_NAME: $PROJECT_NAME"
          else
            echo "🔍 Using provided PROJECT_NAME: $PROJECT_NAME"
          fi
          
          cdk deploy AmericasBloodCentersBedrockStack --require-approval never \
            --context projectName="$PROJECT_NAME" \
            --context modelId="$MODEL_ID" \
            --context embeddingModelId="$EMBEDDING_MODEL_ID" \
            --outputs-file outputs.json
          
          if [ $? -ne 0 ]; then
            echo "❌ ERROR: CDK deployment failed"
            exit 1
          fi
          
          echo "✅ CDK deployment successful"
          
          echo "=== Extracting CDK Outputs ==="
          STACK_NAME="AmericasBloodCentersBedrockStack"
          DOCUMENTS_BUCKET=$(cat outputs.json | jq -r '.AmericasBloodCentersBedrockStack.DocumentsBucketName // empty')
          KB_ID=$(cat outputs.json | jq -r '.AmericasBloodCentersBedrockStack.KnowledgeBaseId // empty')
          S3_DS_ID=$(cat outputs.json | jq -r '.AmericasBloodCentersBedrockStack.S3DataSourceId // empty')
          WEB_DS_ID=$(cat outputs.json | jq -r '.AmericasBloodCentersBedrockStack.WebDataSourceId // empty')
          API_URL=$(cat outputs.json | jq -r '.AmericasBloodCentersBedrockStack.ApiGatewayUrl // empty')
          OPENSEARCH_ENDPOINT=$(cat outputs.json | jq -r '.AmericasBloodCentersBedrockStack.OpenSearchCollectionEndpoint // empty')
          
          if [ -z "$DOCUMENTS_BUCKET" ] || [ -z "$KB_ID" ] || [ -z "$API_URL" ]; then
            echo "❌ ERROR: Failed to extract required outputs from CDK deployment"
            echo "Documents Bucket: $DOCUMENTS_BUCKET"
            echo "Knowledge Base ID: $KB_ID"
            echo "API URL: $API_URL"
            exit 1
          fi
          
          echo "✅ Outputs extracted successfully"
          echo "  📁 Documents Bucket: $DOCUMENTS_BUCKET"
          echo "  🧠 Knowledge Base ID: $KB_ID"
          echo "  📄 S3 Data Source ID: $S3_DS_ID"
          echo "  🌐 Web Data Source ID: $WEB_DS_ID"
          echo "  🌐 API Gateway URL: $API_URL"
          echo "  🔍 OpenSearch Endpoint: $OPENSEARCH_ENDPOINT"
          
          echo ""
          echo "=== Starting Knowledge Base Ingestion ==="
          
          # Start S3 ingestion job for PDFs
          echo "Starting S3 ingestion job for PDFs..."
          S3_INGESTION_JOB_ID=$(aws bedrock-agent start-ingestion-job \
            --knowledge-base-id "$KB_ID" \
            --data-source-id "$S3_DS_ID" \
            --description "Initial ingestion of PDF documents" \
            --region "$CDK_DEFAULT_REGION" \
            --query 'ingestionJob.ingestionJobId' --output text)
          
          echo "✓ S3 ingestion job started: $S3_INGESTION_JOB_ID"
          
          # Start Web Crawler ingestion job
          echo "Starting Web Crawler ingestion job..."
          WEB_INGESTION_JOB_ID=$(aws bedrock-agent start-ingestion-job \
            --knowledge-base-id "$KB_ID" \
            --data-source-id "$WEB_DS_ID" \
            --description "Initial crawling of America's Blood Centers websites" \
            --region "$CDK_DEFAULT_REGION" \
            --query 'ingestionJob.ingestionJobId' --output text)
          
          echo "✓ Web Crawler ingestion job started: $WEB_INGESTION_JOB_ID"
          
          echo ""
          echo "========================================="
          echo "✅ Deployment Complete!"
          echo "========================================="
          echo "🧠 Knowledge Base ID: $KB_ID"
          echo "📄 S3 Data Source ID: $S3_DS_ID (PDFs with Bedrock Data Automation)"
          echo "🌐 Web Crawler Data Source ID: $WEB_DS_ID (Websites)"
          echo "📁 Documents Bucket: $DOCUMENTS_BUCKET"
          echo "🔍 OpenSearch Endpoint: $OPENSEARCH_ENDPOINT"
          echo "📊 S3 Ingestion Job ID: $S3_INGESTION_JOB_ID"
          echo "🕷️ Web Ingestion Job ID: $WEB_INGESTION_JOB_ID"
          echo "🌐 API Gateway URL: $API_URL"
          echo "========================================="
          echo ""
          echo "========================================="
          echo "🚀 Next Steps"
          echo "========================================="
          echo "1️⃣ Wait 5-10 minutes for ingestion jobs to complete"
          echo ""
          echo "2️⃣ Test the API:"
          echo "   curl -X POST $API_URL \\"
          echo "     -H 'Content-Type: application/json' \\"
          echo "     -d '{\"message\":\"How many people donate blood?\",\"language\":\"en\"}'"
          echo ""
          echo "3️⃣ Test Spanish support:"
          echo "   curl -X POST $API_URL \\"
          echo "     -H 'Content-Type: application/json' \\"
          echo "     -d '{\"message\":\"¿Cuántas personas donan sangre?\",\"language\":\"es\"}'"
          echo ""
          echo "4️⃣ Monitor ingestion jobs:"
          echo "   # S3 Data Source (PDFs):"
          echo "   aws bedrock-agent get-ingestion-job \\"
          echo "     --knowledge-base-id $KB_ID \\"
          echo "     --data-source-id $S3_DS_ID \\"
          echo "     --ingestion-job-id $S3_INGESTION_JOB_ID \\"
          echo "     --region $CDK_DEFAULT_REGION"
          echo ""
          echo "   # Web Crawler Data Source:"
          echo "   aws bedrock-agent get-ingestion-job \\"
          echo "     --knowledge-base-id $KB_ID \\"
          echo "     --data-source-id $WEB_DS_ID \\"
          echo "     --ingestion-job-id $WEB_INGESTION_JOB_ID \\"
          echo "     --region $CDK_DEFAULT_REGION"
          echo ""
          echo "5️⃣ Add more documents:"
          echo "   # Add PDFs (uses Bedrock Data Automation parser):"
          echo "   aws s3 cp document.pdf s3://$DOCUMENTS_BUCKET/pdfs/"
          echo "   aws bedrock-agent start-ingestion-job \\"
          echo "     --knowledge-base-id $KB_ID \\"
          echo "     --data-source-id $S3_DS_ID \\"
          echo "     --region $CDK_DEFAULT_REGION"
          echo ""
          echo "   # Re-crawl websites (automatic parsing):"
          echo "   aws bedrock-agent start-ingestion-job \\"
          echo "     --knowledge-base-id $KB_ID \\"
          echo "     --data-source-id $WEB_DS_ID \\"
          echo "     --region $CDK_DEFAULT_REGION"
          echo ""
          echo "📊 Monitor resources:"
          echo "  • Knowledge Base: https://console.aws.amazon.com/bedrock/home?region=${CDK_DEFAULT_REGION}#/knowledge-bases"
          echo "  • OpenSearch: https://console.aws.amazon.com/aos/home?region=${CDK_DEFAULT_REGION}#opensearch/collections"
          echo "  • S3 Bucket: https://s3.console.aws.amazon.com/s3/buckets/$DOCUMENTS_BUCKET"
          echo ""
          echo "💰 Estimated monthly cost: \$8-20 (vs \$20+ for Q Business)"
          echo "🎯 Features: Dual data sources, bilingual support, automatic web crawling, markdown support"
          echo ""
        fi

  post_build:
    commands:
      - echo "========================================="
      - echo "🎉 Deployment Complete"
      - echo "========================================="
      - |
        if [ "$ACTION" = "deploy" ]; then
          echo "✅ Bedrock chatbot deployed successfully"
          echo "📊 Check CloudWatch Logs for Lambda execution details"
          echo "🧠 Test Knowledge Base retrieval via the chat API"
          echo "🌐 Monitor ingestion jobs in Bedrock console"
        else
          echo "✅ Stack destroyed successfully"
        fi

artifacts:
  files:
    - "**/*"
  base-directory: "Backend/cdk.out"